FROM debian:trixie-20260223-slim

LABEL maintainer="46285520+sfmunoz@users.noreply.github.com"

WORKDIR /workspace

RUN apt-get update && \
  apt-get install -y --no-install-recommends \
    git gh jq curl ca-certificates procps sudo less iputils-ping && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

ARG USER_ID=1002
ARG GROUP_ID=1002

RUN groupadd -g ${GROUP_ID} g${GROUP_ID} && \
  useradd -u ${USER_ID} -g ${GROUP_ID} -d /workspace -s /bin/bash u${USER_ID}
